import './styles/reset.css';
import './styles/global.css';
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";


const poppins=Poppins({
  weight:['400','500','600'],
  subsets:['latin'],
  style:['normal']
})

export const metadata: Metadata = {
  title: "Main page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header/>
        <main className='contain'>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
